### ISSUE TITLE
scipy.misc.toimage deprecated

### ISSUE THREAD

**Issue by koenvangils** [MedPhysQC/DX_Normi13#3]
scipy.misc.toimage is deprecated. Because of this the script does not work on a fresh WAD install on Ubuntu 20.04 LTS.  Pillow’s Image.fromarray can be used in stead. See https://docs.scipy.org/doc/scipy-1.2.1/reference/generated/scipy.misc.toimage.html .

**Comment by asch99** [comment]
Already fixed in #db8c2eda72bda09c7cb75af74e8e41b22967f362 and available in pre-release (as needed WAD-QC update is not yet released, but you have it).
